[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
numReplicas = 1

[env]
NODE_ENV = "production"
PORT = "3000" 